"""
provenance_lib.py
=============================================================================
Shared cross-phase provenance stamping, added 2026-08-11 after Phase 7
(09_physics_validation_rajasthan.py) caught Phase 5's and Phase 6's outputs
disagreeing on which PCMs belonged to which cluster_id — traced to
05_cluster_rajasthan.py's GMM cluster labels not being stable across
separate re-runs (fixed there via canonical relabeling by mean latitude,
see that script's own 2026-08-11 note), compounded by Phase 5 and Phase 6
having been run from two DIFFERENT invocations of 05_cluster_rajasthan.py
against two different PROFILE_FILE states.

The canonical-relabeling fix in 05_cluster_rajasthan.py prevents this for
an EQUIVALENT partition re-fit with the same points. It does NOT protect
against Phase 5 and Phase 6 simply being run against two genuinely
DIFFERENT on-disk versions of cluster_profiles_{state}.csv (e.g. someone
re-runs 05, then only re-runs 07, forgetting 08, or vice versa) — that is
a workflow/sequencing risk, not a labeling-algorithm risk, and no amount
of canonical relabeling inside 05 can catch it. This module exists to
catch THAT: every downstream phase that depends on cluster_profiles_
{state}.csv fingerprints the exact file it read, stamps that fingerprint
into its own output, and the NEXT phase in the chain HARD-FAILS (does not
warn-and-continue) if the fingerprint it computes from the CURRENT
on-disk file doesn't match what the phase before it actually consumed.

Usage pattern (see 07/08/09_*.py for the actual wiring):
  # Phase 5 (consumer of cluster_profiles_{state}.csv):
  fp = file_fingerprint(PROFILE_FILE)
  df["upstream_cluster_profile_fingerprint"] = fingerprint_id(fp)
  df.to_csv(OUTPUT_FILE, index=False)

  # Phase 6 (consumer of Phase 5's output AND cluster_profiles_{state}.csv):
  current_fp_id = fingerprint_id(file_fingerprint(PROFILE_FILE))
  assert_fingerprint_match(current_fp_id, survivors_df, PROFILE_FILE.name,
                            SURVIVORS_FILE.name)
  df["upstream_cluster_profile_fingerprint"] = current_fp_id
  df.to_csv(OUTPUT_FILE, index=False)

  # Phase 7 (consumer of Phase 5's AND Phase 6's outputs):
  current_fp_id = fingerprint_id(file_fingerprint(PROFILE_FILE))
  assert_fingerprint_match(current_fp_id, survivors_df, PROFILE_FILE.name, SURVIVORS_FILE.name)
  assert_fingerprint_match(current_fp_id, mcdm_df, PROFILE_FILE.name, MCDM_RANKINGS_FILE.name)
"""

from pathlib import Path


def file_fingerprint(path):
    """mtime + size + row_count — same lightweight convention already
    used by 03b_quality_check_rajasthan.py's own file_fingerprint()
    (not a full-file content hash — see that script's docstring for why
    a full hash was judged unnecessary overhead for files this pipeline
    fully regenerates on every run rather than patches in place)."""
    path = Path(path)
    stat = path.stat()
    with open(path, "r", encoding="utf-8") as f:
        row_count = sum(1 for _ in f) - 1   # minus header
    return {
        "path": str(path),
        "mtime": stat.st_mtime,
        "size_bytes": stat.st_size,
        "row_count": row_count,
    }


def fingerprint_id(fp):
    """Collapses a file_fingerprint() dict into one short deterministic
    string, suitable for embedding as a single repeated column value in
    a downstream CSV (a full dict/JSON blob per row would be noisy)."""
    return f"{fp['size_bytes']}_{fp['row_count']}_{fp['mtime']:.3f}"


def assert_fingerprint_match(current_fp_id, upstream_df, source_file_name, upstream_file_name,
                              fp_column="upstream_cluster_profile_fingerprint"):
    """HARD-FAILS (raises SystemExit) if upstream_df's stamped fingerprint
    doesn't match the CURRENT on-disk fingerprint of source_file_name —
    i.e. if the file upstream_df was originally built from has since
    changed (regenerated by a later, different run of whatever phase
    produces it). This is intentionally a hard stop, not a printed
    warning that lets execution continue — a warning is exactly what let
    a fully-computed, fully-reported Phase 7 result get built on
    mismatched Phase 5/Phase 6 inputs on 2026-08-11."""
    if fp_column not in upstream_df.columns:
        raise SystemExit(
            f"ERROR: {upstream_file_name} has no '{fp_column}' column — it predates this "
            f"provenance-stamping fix (2026-08-11). Re-run the phase that produces "
            f"{upstream_file_name} to add it before this check can run.")
    stamped = upstream_df[fp_column].unique()
    if len(stamped) != 1:
        raise SystemExit(
            f"ERROR: {upstream_file_name} has {len(stamped)} distinct '{fp_column}' values "
            f"(expected exactly 1, constant per file) — it looks like rows from more than one "
            f"run got concatenated into this file. Regenerate it from a single run.")
    stamped_fp_id = stamped[0]
    if stamped_fp_id != current_fp_id:
        raise SystemExit(
            f"ERROR: PROVENANCE MISMATCH — {upstream_file_name} was built from a version of "
            f"{source_file_name} with fingerprint {stamped_fp_id!r}, but the CURRENT on-disk "
            f"{source_file_name} has fingerprint {current_fp_id!r}. This means {source_file_name} "
            f"was regenerated (re-run) AFTER {upstream_file_name} was produced from it — the two "
            f"files are no longer describing the same clustering run. Re-run the full Phase "
            f"4->5->6->7 chain back-to-back from the CURRENT {source_file_name} before trusting "
            f"any result downstream of this point. (This is exactly the class of bug caught in "
            f"Phase 7 on 2026-08-11 — see 09_physics_validation_rajasthan.py's docstring.)")
